=== Sevilda/DW9YG6xmlGyak/Feleves_feladat/hospital.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="location" type="xs:string" />
	<xs:element name="name" type="xs:string" />
	<xs:element name="firstname" type="xs:string" />
	<xs:element name="lastname" type="xs:string" />
	<xs:element name="birthdate" type="xs:string" />
	<xs:element name="allergy" type="xs:string" />
	<xs:element name="price" type="xs:short" />
	<xs:element name="quantity" type="xs:short" />
	<xs:element name="condition" type="xs:string" />
	<xs:element name="admission-date" type="xs:date" />
	<xs:element name="specializing" type="xs:string" />
	
	<xs:element name="employed" type="xs:IDREF" />
	<xs:element name="patient-id" type="xs:IDREF" />
	<xs:element name="ward-id" type="xs:IDREF" />
	<xs:element name="medicine-id" type="xs:IDREF" />


	<xs:element name="hospital">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ward" maxOccurs="unbounded" />
				<xs:element ref="patient" maxOccurs="unbounded" />
				<xs:element ref="doctor" maxOccurs="unbounded" />
				<xs:element ref="medicine" maxOccurs="unbounded" />
				<xs:element ref="treatment" maxOccurs="unbounded" />
				<xs:element ref="prescription" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="ward">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="location" />
			</xs:sequence>
			<xs:attribute type="xs:ID" name="id" use="required" />
		</xs:complexType>
	</xs:element>


	<xs:element name="patient">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="fullname" />
				<xs:element ref="birthdate" />
				<xs:element ref="allergy" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute type="xs:ID" name="id" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="fullname">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="firstname" minOccurs="1" />
				<xs:element ref="lastname" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>



	<xs:element name="doctor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fullname" />
				<xs:element ref="birthdate" />
				<xs:element ref="specializing" minOccurs="0" />
				<xs:element ref="employed" />
			</xs:sequence>
			<xs:attribute type="xs:ID" name="id" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="medicine">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="price" />
			</xs:sequence>
			<xs:attribute type="xs:ID" name="id" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="treatment">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="patient-id" />
				<xs:element ref="ward-id" />
				<xs:element ref="condition" minOccurs="0" />
				<xs:element ref="admission-date" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="prescription">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="patient-id" />
				<xs:element ref="medicine-id" />
				<xs:element ref="quantity" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== Sevilda/DW9YG6xmlGyak/Feleves_feladat/hospital.xml
<?xml version="1.0" encoding="utf-8"?>
<hospital xmlns:xsi="https://w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="hospital.xsd">

	<ward id="wardccu">
		<name>CCU</name>
		<location>North Wing</location>
	</ward>
	<ward id="wardrehab">
		<name>Rehabilitation</name>
		<location>Southwest Wing</location>
	</ward>
	
	<patient id="pat23">
		<fullname>
			<firstname>John</firstname>
			<lastname>Wick</lastname>
		</fullname>
		<birthdate>1993-03-02</birthdate>
		<allergy>Lactose</allergy>
		<allergy>penicillin</allergy>
	</patient>
	<patient id="pat92">
		<fullname>
			<firstname>Mike</firstname>
			<lastname>Ritch</lastname>
		</fullname>
		<birthdate>1978-06-30</birthdate>
		<allergy>Gluten</allergy>
	</patient>
	
	<doctor id="doc6">
		<fullname>
			<firstname>Charles</firstname>
			<lastname>Schultz</lastname>
		</fullname>
		<birthdate>1965-11-11</birthdate>
		<specializing>Pediatrics</specializing>
		<employed>wardccu</employed>
	</doctor>
	<doctor id="doc21">
		<fullname>
			<firstname>Celestina</firstname>
			<lastname>Warbeck</lastname>
		</fullname>
		<birthdate>1970.01.01</birthdate>
		<employed>wardccu</employed>
	</doctor>
	
	<medicine id="medpain1">
		<name>Aspirin</name>
		<price>2000</price>	
	</medicine>
	<medicine id="medlax5">
		<name>Ducolax</name>
		<price>300</price>	
	</medicine>
	<medicine id="medanx4">
		<name>Xanax</name>
		<price>666</price>	
	</medicine>
	
	<treatment>
		<patient-id>pat23</patient-id>
		<ward-id>wardccu</ward-id>
		<condition>arrhythmia</condition>
		<admission-date>2020-06-08</admission-date>
	</treatment>
	<treatment>
		<patient-id>pat92</patient-id>
		<ward-id>wardrehab</ward-id>
		<admission-date>2020-10-13</admission-date>
	</treatment>
	
	<prescription>
		<patient-id>pat92</patient-id>
		<medicine-id>medlax5</medicine-id>
		<quantity>30</quantity>
	</prescription>
	<prescription>
		<patient-id>pat92</patient-id>
		<medicine-id>medanx4</medicine-id>
		<quantity>20</quantity>
	</prescription>
	<prescription>
		<patient-id>pat23</patient-id>
		<medicine-id>medanx4</medicine-id>
		<quantity>60</quantity>
	</prescription>
	

</hospital>
