=== Sevilda/DW9YG6xmlGyak/201008/VE_orarend.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="orarend">
		<xs:complexType>
		<xs:sequence>
			<xs:element name="ora" maxOccurs="unbounded" type="oratipus"/>
		</xs:sequence>
		</xs:complexType>
	</xs:element>
				
				
	<xs:complexType name="oratipus">
		<xs:sequence>
			<xs:element name="targy" type="xs:string"/>	
			<xs:element name="idopont" maxOccurs="unbounded" type="idoponttipus"/>
			<xs:element name="helyszin" maxOccurs="unbounded" type="xs:string" />
			<xs:element name="oktato" type="xs:string"/>
			<xs:element name="szak" type="xs:string"/>	
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required"/>
		<xs:attribute name="tipus" type="oratipusTipus" default="eloadas"/>
	</xs:complexType>
	
	<xs:complexType name="idoponttipus">				
		<xs:sequence>
			<xs:element name="nap" />
			<xs:element name="tol" type="idopontoraTipus" />
			<xs:element name="ig" type="idopontoraTipus" />
		</xs:sequence>
		<xs:attribute name="day">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="h|k|s|c" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	
	<xs:simpleType name="oratipusTipus">
		<xs:restriction base="xs:string">
			<xs:pattern value="gyakorlat|eloadas" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="idopontoraTipus">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="8" />
			<xs:maxInclusive value="19" />
		</xs:restriction>	
	</xs:simpleType>



	
	</xs:schema>

=== Sevilda/DW9YG6xmlGyak/201001/VE_orarend.xml
<?xml version="1.0" encoding="UTF-8"?>

<orarend 
	xmlns:xsi="https://w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="VE_orarend.xsd">
	<ora id="ora_id_1" tipus="eloadas">
		<targy> Szoftver teszteles</targy>
		<idopont day="h">
			 <nap> hetfo </nap> 
			 <tol> 8 </tol>
			 <ig> 12 </ig>
		</idopont>
        <helyszin> IIT 101 </helyszin>
        <oktato> Tompa T. </oktato>
		<szak> KWT </szak>	
	</ora>
	
	<ora id="ora_id_2" tipus="gyakorlat">
		<targy>Mesterseges Intelligenciak</targy> 
            <idopont day="h">
			 <nap> Hetfo </nap> 
			 <tol> 12 </tol>
			 <ig> 15 </ig>
		</idopont>
        <helyszin>A_305 </helyszin>
        <oktato > Dudas L.</oktato>
		<szak> KWT </szak>
	</ora>	
		
	<ora id="ora_id_3" tipus="gyakorlat">
        <targy> Web Technologiak </targy>
			<idopont day="h">
			 <nap> Hetfo </nap> 
			 <tol> 15 </tol>
			 <ig> 18 </ig>
		</idopont>
        <helyszin> IIT_103</helyszin>
        <oktato>Agardi A. </oktato>
		<szak> KWT </szak>	
	</ora>
	
	<ora id="ora_id_4" tipus="gyakorlat">
		<targy>Web Alk Javaban</targy>
		<idopont day="k">
			 <nap> Kedd </nap> 
			 <tol> 12 </tol>
			 <ig> 14 </ig>
		</idopont>	
        <helyszin >103</helyszin>
        <oktato>Bednarik L.</oktato>
		<szak> KWT </szak>	
	</ora>
	
	<ora id="ora_id_5" tipus="eloadas">
		<targy>Adatkezeles XML ben </targy>
		<idopont day="k">
			 <nap> Kedd </nap> 
			 <tol> 12 </tol>
			 <ig> 14 </ig>
		</idopont>	
		<helyszin> 305</helyszin>
		<oktato> Bednarik L.</oktato>
		<szak> KWT </szak>	
	</ora>
	
	<ora id="ora_id_6" tipus="eloadas">
        <targy>Integralt Vallalati Rdsz.-ek</targy>
		<idopont day="s">
			 <nap> Szerda </nap> 
			 <tol> 12 </tol>
			 <ig> 16 </ig>
		</idopont>
		<helyszin>A_319</helyszin>
        <oktato> Samad D.</oktato>
		<szak> KWT </szak>	
	</ora>
</orarend>
