=== Sevilda/DW9YG6xmlGyak/DW9YG6_1015/ERkonvSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="ER">
		<xs:complexType>
			<xs:all>
				<xs:element name="A" type="aType" />
				<xs:element name="B" type="bType" />
				<xs:element name="C" type="cType" />
				<xs:element name="AtoB" type="atoBType" />
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="aType">
		<xs:choice>
			<xs:element name="b" type="a_bType" maxOccurs="unbounded" />
			<xs:element name="c" type="xs:string"/>
		</xs:choice>
		<xs:attribute name="a_k"  type="xs:int"/>
		<!-- id -->
	</xs:complexType>

	<xs:complexType name="a_bType">
		<xs:choice>
			<xs:element name="x" type="xs:string" />
			<xs:element name="y" type="xs:string" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="bType">
		<xs:choice>
			<xs:element name="b" type="a_bType" />
		</xs:choice>
		<xs:attribute name="a" type="xs:int" />
		<!-- id -->
	</xs:complexType>

	<xs:complexType name="cType">
		<xs:choice>
			<xs:element name="a" type="xs:string" />
			<xs:element name="b" type="xs:string" />
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="atoBType" mixed="true">
			<xs:choice>
				<xs:element name="c" type="xs:string"/>
			</xs:choice>
			<xs:attribute name="aID" type="xs:int"/>
			<xs:attribute name="bID" type="xs:int"/>
	</xs:complexType>
	

	

</xs:schema>

=== Sevilda/DW9YG6xmlGyak/DW9YG6_1008/ERkonvSchema.xml
<?xml version="1.0" encoding="utf-8"?>

<ER xmlns:xsi="https://w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ERkonvSchema.xsd">

	<A a="aID">
		<!-- b is a multivalued -->
		<b>
			<x> Content </x>
			<y> Content </y>
		</b>
		<b>
			<x> Content </x>
			<y> Content </y>
		</b>
		<c> Unnamed composites</c>
	</A>

	<B a="bID">
		<b>
			<x> Content </x>
			<y> Content </y>
		</b>
	</B>

	<C a="cID">
		<b />
		<!-- Afaik C to B relation is detailed in here as it is the '1' side of 
			the relation. !! will ask about it later -->
		<bID />
	</C>


	<AtoB aID="" bID="">
		<c> Content </c>
	</AtoB>

</ER>
